### ISSUE TITLE
Make Action Cable and Listen optional dependencies

### ISSUE THREAD

**Issue by agrobbin** [ViewComponent/lookbook#183]
First off, really appreciate the work already done on Lookbook!

Auto-refresh as a feature is convenient, but the dependencies required to support it are not insignificant (Action Cable and Listen). I'm curious what appetite there is for inverting the default configuration, and making these 2 dependencies _optional_, rather than _required_.

Similar to Rails itself, which offers optional Listen integration for evented class reloading ([documentation](https://github.com/rails/rails/blob/v7.0.4/guides/source/configuring.md#configfile_watcher)), it seems more in line with the community conventions to offer this kind of support, but not make it a requirement of all Lookbook users.

An important note... this suggestion would definitely be backwards-incompatible, and likely necessitate a major version bump. That said, I still thought it worth proposing!

**Comment by allmarkedup** [comment]
Hey @agrobbin, thanks for starting a discussion around this!

I'm certainly up for making some dependencies optional where possible to slim down the size of Lookbook - I will confess it has not been a priority of mine with the project so far but I'd very much like to see what I can do to help Lookbook be a better match for people's requirements, where possible.

Action cable could definitely be one of those as all that is used for is for notifying the frontend that a change has occurred and so triggering a refresh. If people were happy to have the option to manually refresh instead then not including it would be no problem.

The Listen dependency is more difficult to remove however, because it not only plays it's part in letting the UI know it needs to update itself but it also is used to trigger a re-parsing of the component preview files in the background. Without listening for changes, this would have to be done on every request (as Lookbook wouldn't know if a file had been changed since the last request). For larger projects that parsing step can be quite slow, which would quickly make the UI very sluggish and frustrating to use.

Having said that... thinking about it now I guess it could be possible to compare the modification times of all the files to see if any have changed since the last request, and only re-parse if required? I'd need to do a little work to validate that but it should be possible. It would likely still impact the performance but may be a good fallback option even for the current setup if people are having problems with the file change listeners.

It would definitely be a breaking change but I'll look into it as something to potentially include in the next major version release if I can figure something out. I'll label this as a feature request and try and do a bit of a spike when I have a chance.

Thanks again for the suggestion :-)

**Comment by agrobbin** [comment]
@allmarkedup thanks for the thoughtful response! My only follow-up here is to elaborate a bit on the use case I have for Lookbook. While it's definitely possible the usage may change over time, at present, Lookbook is not something kept over continuously, or expected to be live-updated. Instead, it's used as a reference for UI components, when building features on top of the design system. It's for that reason that the auto-refreshing of the UI is not currently beneficial.

As for the additional uses of Listen, I do wonder what kind of performance hit we're talking about. Action View itself reloads templates in non-production environments (technically whenever `config.cache_classes` is `false`, via [`config.action_view. cache_template_loading`](https://guides.rubyonrails.org/configuring.html#config-action-view-cache-template-loading)), so I'm curious what kind of impact a simpler implementation would have.

**Comment by allmarkedup** [comment]
@agrobbin ok thank you for the context, that is good to know - I must admit I hadn't really considered that use case but it's something I'll try to cater for better in the future. It's really great to get a better view on how Lookbook is being used differently in different projects so I appreciate you getting back to me :-)

I have not done any work to quantify the performance hit to be honest but it's not quite as straightforward as just reloading the classes/templates - Lookbook uses YARD under the hood to do the parsing of annotations so that has to run as a separate step each time a change happens. But there are plenty of optimisations to be made to the current implementation (which is really well overdue a proper re-write!) so it may end up being not such a big hit after all.

**Comment by allmarkedup** [comment]
Hey @agrobbin 👋

I just wanted to let you know that I've just released a [first beta of Lookbook v2.0](https://github.com/ViewComponent/lookbook/discussions/310) which includes (among other things) a completely new file watching/live updates system. And following on from your suggestion, `actioncable` and `listen` are now optional dependencies and no longer come bundled with Lookbook.

I was skeptical this could work initially but your query prompted me to look at it all again and I've ended up finding a way to piggyback much more heavily on the class reloading and file watching systems that are built into Rails already.

Aside from facilitating the move of `listen` and `actioncable` to optional dependencies, the deeper Rails integration has provided many unforseen additional benefits - including fixing a number of concurrency/forked process issues that I did not think would be possible to fix! (With my level of Ruby knowledge, anyway).

So I just wanted to say thank you for prompting me to think a little harder about this issue because I'm now quite excited about the new approach and I think it's going to help clear up a number of previously hard to address bugs that have been frustrating people! 

If you have any time to give the beta a try I'd be interested to hear any feedback you might have on it. It's just a first release so there may be some kinks to work through but if you are feeling brave then do give it a spin :-)

A few useful links in case you want to dive in:

* v2.0 release discussion thread: https://github.com/ViewComponent/lookbook/discussions/310
* Updated docs, upgrade guide and more: https://v2.lookbook.build (still a work in progress)
* [v2.0 Lookbook UI demo](https://v2-demo.lookbook.build/lookbook) and some [examples of preview embeds](http://v2-demo.lookbook.build/embeds), one of the main new features in v2.0.

I'll close this issue down now but if you have any questions about anything just let me know.

**Comment by agrobbin** [comment]
@allmarkedup that is great to hear! I've just taken a (quick) look at the 2.0 beta on my application, and things are looking great. I also took a brief look at the reloader changes you made, and am really excited about the use of what Rails provides to you!

I appreciate the "thank you", and want to pass along my thanks as well, as I think this will make Lookbook even more compelling to even more people/use cases!

**Comment by allmarkedup** [comment]
Ah fantastic - thanks for letting me know :-) And have a good weekend!
