### ISSUE TITLE
Add a "iframe-friendly" layout, maybe?

### ISSUE THREAD

**Issue by thutterer** [ViewComponent/lookbook#185]
:wave: Hi Mark,

we are thinking about a somewhat unusual way to use Lookbook, and I want to share it, and ask if this is something you would consider supporting. It might be too specific to justify the required changes, but who knows :shrug: 

We at GitLab have our design system documented at https://design.gitlab.com/ and all our components are available already as Vue.js components. To make it possible to use our design system also in the server-side rendered parts of the application, we've started to implement ViewComponents as well.

Now, in our documentation site, each component page has a tab-navigation, where clicking the "Implementation" tab loads a Storybook for that component in an iframe. See https://design.gitlab.com/components/alert/code as example.

The idea now is to add another tab "Implementation (ViewComponent)" that would load the Lookbook preview of the corresponding ViewComponent, also in an iframe.

But for this use case, we wouldn't want to load the entire Lookbook layout, but only the preview itself, and the drawer, so that the reader can interact with the params, and also read the notes and source code.

I can think of the following ways to approach this:

- Teach Lookbook an alternative "page-only" layout that doesn't render the topbar and sidebar. Probably some effort to implement and maintain this, though.
- Add a new config option that allows to inject an extra stylesheet and leave it up to the user to hide things with `display: none !important` or whatever. Not sure how well that could work though. Definitely at risk to break with a new version of Lookbook.

Ignoring the fact that the first idea would be quite some effort already in itself, we could go further, and completly rethink this second layout. As for our use case, it would actually be best if the Notes section came first, then the preview area (non-resizable), then the params, then the source code. So basically no drawer at all, but all in one top-to-bottom document.

I hope I was able to describe our use case well enough, and really no hard feelings if you think this is something too specific :relaxed: For the time being, we'll just make that new "tab" a link that opens the full Lookbook in a new browser tab.

**Comment by allmarkedup** [comment]
Hey @thutterer - this is an interesting use case for sure, but one I'd love to find a way to support as I think a good, generalised solution to an 'embeddable preview' could be of interest to others, too.

I'm afraid I'm not a fan of the brute-force, injected stylesheet option - I've implemented something similar in the past in a different project and as you say it can quickly become a maintenance headache for both parties.

However some sort of embed-specific view of the preview could work I think. Perhaps even using a layout that the parent app could override to customise what sections were featured and in what order, etc. For example (pseudo-code only!):

```erb
<div>
  <header>
    <h1><%= preview.title %></h1>
  </header>

  <section>
    <%= panel :notes %>
  </section>

  <section>
    <%= preview_window(resizable: false) %>
  </section>

  <section>
    <%= panel :params %>
  </section>
</div>
```

Adding some scoped custom styling could be handled in the same way it is implemented for [custom panels](https://lookbook.build/guide/extend/panels/#styling-panel-content).

I'll need to have a bit more of a think about this but it's definitely piqued my interest. I think the hardest part may be getting the current `@params` implementation to work in an iframe - it may 'just work' out of the box but I'd need to run some tests to dig into it a bit more.

I wouldn't want to build a very specific implementation but if I can find a nice way to make this work for a range of 'embed' use cases it's definitely something I'd be up for adding to Lookbook, time permitting of course :-)

**Comment by thutterer** [comment]
Wow, such a great answer, thank you @allmarkedup :heart_eyes_cat: 

I'm happy you see some potential value and a chance to generalize for other use cases as well. 

Let me know if I can help you in your efforts in any way!

**Comment by allmarkedup** [comment]
Thanks @thutterer, I will certainly let you know whenever I've had a chance to explore the idea a bit and have some more thoughts or something for you to have a play with 😊

**Comment by allmarkedup** [comment]
Hey @thutterer I just wanted to touch base here and let you know I haven't forgotten about this. Actually I've been experimenting a bit and have gone down the route of extending the capabilities of the existing embedded preview component so that it can work both within Lookbook (embedded in documentation pages) and outside of it, rendered in an iframe.

I'm actually getting pretty close to having something that you could have a play with, but I just thought I'd share some info while I'm ironing out some bugs to make sure that it would actually fit your needs and I haven't gotten the wrong end of the stick.

This is more or less what the current within-Lookbook-only embed component looks like:

<img width="727" alt="CleanShot 2022-11-24 at 21 18 36" src="https://user-images.githubusercontent.com/126726/203864210-d97ec83c-c6cd-4465-91c5-a87843518b44.png">

And so I've built on top of that, adding support for all built-in as well as custom panels:

<img width="741" alt="CleanShot 2022-11-24 at 21 17 00" src="https://user-images.githubusercontent.com/126726/203864330-3076e0e9-eacb-4cf0-8d27-01b9bdf9c11c.png">

<img width="742" alt="CleanShot 2022-11-24 at 21 16 46" src="https://user-images.githubusercontent.com/126726/203864334-83a96663-f965-46fa-bdfc-dd8a42f4b8e1.png">

All of these can now be loaded in via an iframe - there is a small piece of JS that needs to be added to the host page to ensure the iframe takes the correct size but apart from that it should be pretty straighforward to embed them outside of Lookbook now I think.

The embeds can be customised via URL parameters on the iframe src - i.e. to hide/show panels for specific instances etc.

I've made a very short video where you can see a component preview embedded in a page on the parent app, outside of Lookbook itself:

https://user-images.githubusercontent.com/126726/203864941-8bf96427-2132-471c-bfa1-0d138bd9bace.mp4

So, the question is - is this the sort of thing that you had in mind? Any suggestions/feedback based on what you've seen here? I have a feeling you were thinking of something a bit more freeform in layout but after exploring a few options I felt like I preferred a more compact, cleaner layout.

I still need to do a bunch of debugging and cleanup work on this so there is plenty of time to make tweaks if you have any ideas. People have been asking for improvements to the embed component for a while so making it work both inside and outside of Lookbook is (hopefully!) killing two birds with one stone. I am interested to know what you think about it so far though :-)

**Comment by thutterer** [comment]
> That is pretty goddamn cool!

My thinking as well! :partying_face: 

Having this will be such a huge improvement over what we have today for our design system. Example: https://design.gitlab.com/components/badge/lookbook

We currently only render the raw VC preview in an iframe and link to the full Lookbook. Having it all embedded as shown in the video would be so awesome!

And I don't really mind that it's not as freeform as I've suggested first. I also see benefits in keeping it more compact. What would be nice to have (but really not that important either) is if we were in control of what is rendered as the first/active tab. For example, if there is a critical piece of documentation in the _Notes_ that we want to show.

> there is a small piece of JS that needs to be added to the host page to ensure the iframe takes the correct size

Is that small piece [iframe-resizer](https://www.npmjs.com/package/iframe-resizer) by any chance? We are using that already :smiley:

**Comment by allmarkedup** [comment]
> What would be nice to have (but really not that important either) is if we were in control of what is rendered as the first/active tab. For example, if there is a critical piece of documentation in the Notes that we want to show.

Yep you will have complete control over which panels to show in the embed (both standard and custom ones available) and in which order they will display in the embed.

> Is that small piece [iframe-resizer](https://www.npmjs.com/package/iframe-resizer) by any chance? 

It is, plus a little extra that will instantiate the embed correctly. Adding an embed will be look something like this:

```html
<!-- add one or more lookbook-embed tags in the page, will be replaced by an iframe -->
<lookbook-embed
  app="//localhost:3000/lookbook"
  preview="Feedback::BlankSlateComponentPreview"
  example="default"
  panels="params,source,output">
</lookbook-embed>

<!-- include JS and init once -->
<script src="lookbook.js"></script>
<script>Lookbook.initEmbeds();</script>
```

The exact syntax may still change a little - I'm just finishing up a few things and testing and then will try to get a demo up soon. But I'm glad it seems to be roughly along the right lines for what you need, I'm already excited about places I can use it myself :-)

**Comment by allmarkedup** [comment]
@thutterer @henrikbjorn I've now got a demo page up with a few different embed examples on it - see what you think: https://lookbook-demo-v2.herokuapp.com/embeds

Embeds are going to be released as part of Lookbook v2.0, I hope to have a first beta release out within a couple of weeks so you can play with it for real :-)

**Comment by thutterer** [comment]
@allmarkedup This is amazing work!! Can't wait for 2.0 :rocket:

**Comment by allmarkedup** [comment]
Hey @thutterer, well it has taken me a LOT longer than I would have liked but I've finally release the first v2.0 beta which includes the preview embeds functionality.

I don't even know if it will still be useful for you but it's been one of my favourite features to build so I am happy :-)

If you have.a chance to try out the beta and let me know how you get on that would be amazing, although I realise that there is never enough time in the day for things like this.

A few useful links:

* v2.0 release discussion thread: https://github.com/ViewComponent/lookbook/discussions/310
* Updated docs, upgrade guide and more: https://v2.lookbook.build (still a work in progress)
* [v2.0 Lookbook UI demo](https://v2-demo.lookbook.build/lookbook) and some [examples of preview embeds](http://v2-demo.lookbook.build/embeds)

Any and all feedback would be most welcome :-)

**Comment by allmarkedup** [comment]
I'm going to close this issue down now as the feature has been implemented, any bugs or suggestions for improvements would be better handled in a fresh thread I think.

**Comment by thutterer** [comment]
Hey @allmarkedup, sorry for the late reply, I had some time off, so I just got your message :snowman: 

> I've finally release the first v2.0 beta which includes the preview embeds functionality

This is awesome! Congrats to a beta release with such nice new features :tada: 

> I don't even know if it will still be useful for you but it's been one of my favourite features to build so I am happy

Happy to hear my idea was a joy to implement. That's not always the case :wink: And this will be definitely super useful to us. Can't wait to update our Lookbook to 2.0

> If you have.a chance to try out the beta and let me know how you get on that would be amazing, although I realise that there is never enough time in the day for things like this.

Right, time... I'm still in the middle of finishing up a couple of other tasks, but I will make some time this week to give the latest beta release a try and report in https://github.com/ViewComponent/lookbook/discussions/310 with my findings.

Have a great Monday Mark and thanks again for your great work on this :clap:

**Comment by allmarkedup** [comment]
No worries at all @thutterer - and no rush! Whenever you've caught up with yourself after your time off is just fine :-)

I look forward to hearing any feedback you might have whenever you've had a chance to give it a spin. Good luck catching up with everything!

**Comment by thutterer** [comment]
Thanks! All caught up :nerd_face: https://github.com/ViewComponent/lookbook/discussions/310#discussioncomment-5012283
