### ISSUE TITLE
Lookbook seem to fail for single HTML closing tag when attributes split over several lines

### ISSUE THREAD

**Issue by strzibny** [ViewComponent/lookbook#214]
### Describe the bug

It looks like Lookbook fails if the component uses markup split over several lines while finished with `/>` on the last one:

```
<img
  src="<%= @avatar_url %>" 
/>
```
(fails)

vs 

```
<img
  src="<%= @avatar_url %>"
>
```
(works)

### To Reproduce

Make any kind of component with a single tag like `img` with attributes split over several lines and finished by `/>` on the last line. 

### Expected behavior

I would expect this to work.

### Screenshots

![Screenshot from 2022-10-28 13-57-35](https://user-images.githubusercontent.com/1395527/198582514-fcdba923-34de-4465-b1ce-2f95f4503dc9.png)

**Comment by allmarkedup** [comment]
Hey @strzibny thanks for the bug report! It looks like this is an issue with the HTML 'beautifier' used by Lookbook under the hood.

I'll try to see if there is a workaround I can implement or at least improve the handling of this situation so that the source code is still rendered and the app doesn't just throw an error like this.

I'll update here as soon as it's fixed.

**Comment by allmarkedup** [comment]
@strzibny Turns out this was an easy one to address :-)

 As I suspected [it's a bug in the HTML beautifier](https://github.com/threedaymonk/htmlbeautifier/issues/68) that is causing it to raise an exception as it thinks the HTML is malformed.

Hopefully the issue will get fixed upstream but until that point I've just [committed a change](https://github.com/ViewComponent/lookbook/commit/18254c2350ffcd7c6a3a26e980cf32b83aa99dfd) to make sure Lookbook rescues the exception and returns the un-formatted HTML instead. It's just a nicety so I think that is a reasonable fallback for now.

The fix will go out in the next release, thanks again for reporting!
