### ISSUE TITLE
Support for Stimulus

### ISSUE THREAD

**Issue by strzibny** [ViewComponent/lookbook#280]
I migrated our components to Lookbook, but I haven't found any documentation regarding running component's JavaScript code in the preview.

As example could be a dropdown, that could expand and hide directly in the preview.

Am I missing something or is this not supported? If it isn't do you have some pointers where to start in an attempt to add this support?

**Comment by allmarkedup** [comment]
Hey @strzibny - ViewComponent previews (and so by extension Lookbook) don't provide any way to explicitly handle the styling or behaviour of your components. It's generally assumed that you are bundling all your assets up and referencing them in your application/preview layout as you would in your 'proper' app.

Obviously that means that you are loading all your bundled assets rather than just those for the current component that is being previewed, so it's not very well encapsulated from that point of view.

If you wanted to load component-specific unbundled, individual asset files into your preview you could try using an `@display` tag (https://lookbook.build/guide/previews/display/) to specify files to include and then reference that in your preview layout. Something like this:

```rb
# @display js_file dropdown.js
class DropdownComponentPreview < ViewComponent::Preview
  # ...
end
```

And reference it in your layout:

```erb
<head>
  <script src="/assets/<%= params[:lookbook][:display][:js_file] %>"></script>
</head>
```

Obviously this is just a rough sketch of how to implement this sort of thing, and in practice I've found that really it gets pretty  complicated very quickly with regards to things like dependencies on other JS files etc. So I personally usually just link to the entire application JS bundle  - which also actually has the benefit of most accurately representing the conditions that the component will run in in the context of the application itself.

If you have any other suggestions or ideas for how you think this could be improved or managed then please do let me know. As described Lookbook is very hands-off in this area but I'd certainly consider adding features to support this sort of thing if there are good ways to do so that don't tie Lookbook to a specific front-end bundler or other technology.

**Comment by allmarkedup** [comment]
@strzibny I'm going to go ahead and close this down now, but if I misunderstood your question or anything still isn't clear just let me know :-)

**Comment by strzibny** [comment]
I am sorry for the late reply, I had this thing opened in mail but still could not get into it.

Thank you so much for the answer, this cleared things for me significantly and I got it working.

Thank you again for the detailed answer.

**Comment by allmarkedup** [comment]
Thats great @strzibny, thanks for letting me know! Glad you have got it all working now :-)
