### ISSUE TITLE
Add the ability to hide a nested within a group.

### ISSUE THREAD

**Issue by cody-clio** [ViewComponent/lookbook#525]
### Is your feature request related to a problem? 

We have a use case in which we are grouping multiple component variants by using the `# @!group ` tag. 

We want the ability to hide certain previews within this group so that do not show in Lookbook but we can still use the preview file for testing purposes. 

Currently adding the `@hidden` label while in a group does not hide the preview. 

### Describe the solution you'd like

When the `@hidden` label is provided within a preview nested in a group, it hides the preview.

**Comment by allmarkedup** [comment]
Hey @cody-clio, thanks for this - this is actually a bug, hidden scenarios should definitely be hidden in groups as well as outside of them.

I'll take a look into it and get it fixed up as soon as I can, should be reasonably straightforward. I'll let you know how I get on.

**Comment by allmarkedup** [comment]
@cody-clio okay so I've looked into this and pushed up a fix so that hidden scenarios within a group are no longer shown in that group.

However they are not currently accessible via their URL (unlike hidden scenarios that are _not_ part of a group). They should be - but it's a bit of a bigger job to get that working because currently the URL->preview lookup doesn't look "inside" groups, and it's unfortunately a little tricky to change that behaviour thanks to a few poor design decisions on my part!

As the full fix will take a little longer I thought I'd at least push up this partial fix first. Once the next release is out I'll close this issue and open another one specifically to track "hidden scenarios within groups are not accessible via their URL" and I'll try and get to it as soon as I can.

**Comment by allmarkedup** [comment]
I've just released v2.1.0 with the first half of this fix (and created another issue to track the second part, linked above) so I'm going to go ahead and close this down now.
