### ISSUE TITLE
Lookbook overrides ViewComponent `show_previews` config depending on load order

### ISSUE THREAD

**Issue by ariel-codes** [ViewComponent/lookbook#559]
### Describe the bug

If Lookbook is before ViewComponent in the Gemfile, Lookbook overrides `config.view_component.show_previews` to `true`.

### Repo
https://github.com/ariel-codes/vc_preview_false 

### Steps to reproduce the behavior

In a Rails app generated with `rails new --minimal`
1. Add this to `Gemfile`
```ruby
gem "lookbook"
gem "view_component"
```
3. Add this to `config/application.rb`
```ruby
config.view_component.show_previews = false
```
5. Start `bin/rails s` and navigate to `http://localhost:3000/rails/view_components/`

### Expected behavior

Navigation should result in a 404, but instead shows ViewComponent previews.

### Version numbers 

Please complete the following information:

* Lookbook: 2.2.0
* ViewComponent: 2.82.0
* Rails: 7.1.2
* Ruby: 3.2.2

**Comment by ariel-codes** [comment]
Maybe this isn't a bug per se – but there should be a warning on the docs since this could make VC previews available in cases that aren't desirable, such as in production.

**Comment by allmarkedup** [comment]
Hey @ariel-codes, this is intentional as Lookbook requires ViewComponent previews to be available in order to render some previews correctly. 

However you are totally correct - there should be a warning in the docs about this. I'll add one in when I get a chance.

I would generally recommend only loading the Lookbook gem in development if you are not using it in production:

```rb
group :development do
  gem "lookbook"
end
```

But regardless as it is silently overriding the ViewComponent config option this should be noted somewhere. Thanks for the suggestion :)

**Comment by allmarkedup** [comment]
@ariel-codes I've just added a note about this behaviour [to the docs](https://lookbook.build/guide/components/view_component#:~:text=Note%20that%20Lookbook,ViewComponent%20preview%20URLs.) so I'm going to go ahead and close this issue now. Thanks again for bringing it to my attention!
